import { createSlice } from '@reduxjs/toolkit';

const initialState = {
    token : null,
    isAuthenticated: false,
}

const authSlice = createSlice({
    name : 'auth',
    initialState,
    reducers: {
        // When an action like login is dispatched, the reducer updates the token and isAuthenticated fields.
        login : (state, action) => {
            console.log(action);
            console.log("Current state in login reducer:", state);
            console.log("Action payload in login reducer:", action.payload);
            state.token = action.payload.token;
            state.isAuthenticated = true;
            console.log("Updated state in login reducer:", state);
        },
        logout : (state, action) => {
            state.token = null;
            state.isAuthenticated = false;
        },
    }
})

// 	login and logout are action creators automatically generated by createSlice.
export const { login , logout} = authSlice.actions;
export default authSlice.reducer;